services:
  - type: web
    name: webdis
    env: docker
    region: oregon
    plan: standard
    branch: main
    rootDir: realworld
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false