services:
  - type: web
    name: webdis
    env: docker
    region: oregon
    plan: standard
    branch: main
    rootDir: realworld
    healthCheckPath: /
    envVars:
      - key: DB_URL
      - fromDatabase:
          name: prod
          property: host
      - key: DB_USER
      - fromDatabase:
          name: prod
          property: user
      - key: DB_PASSWORD
      - fromDatabase:
          name: prod
          property: password